### PR TITLE
Feature/interpretation ckeditor

### PR DESCRIPTION
**Pull request by tokland**
(Requires https://github.com/dhis2/d2-analysis/pull/60)

I used `vendorScripts` to load the required `ckeditor.js`, I've ported the code from https://github.com/dhis2/maintenance-app.

Once we validate this PR, I'll copy the same code to the other analytic apps.

### CODE REVIEW

**Comment by edoardo** [comment]
Please fix the conflicts.

**Comment by tokland** [comment]
Done, ready for testing and merging.

**Comment by edoardo** [comment]
The app does not load when I try locally.
I get this error in the console:

screen shot 2018-05-31 at 09 25 14

**Comment by tokland** [comment]
Did you pull changes in charts-app? A commit there now loads CKEditor synchronously, which is required bye this plugin.

https://github.com/dhis2/charts-app/pull/39/commits/2088565deda0003eee79b4d163ecc34ad1ea4712

**Comment by edoardo** [comment]
There is still one problem with this.
Dashboard app does not load charts due to the same error because the plugin does not load the editor.
The plugin does not need the editor library as it will never show the interpretation panel.

The best would be to avoid loading unnecessary libraries in the plugins and change the code so that the editor is only initialized/used in the full app.

**Comment by tokland** [comment]
My bad, I forgot about the plugin. I'll fix this now.

**Comment by tokland** [comment]
Adding a `+if (!window.CKEDITOR) return;` to the ckeditor plugin works, but I guess you prefer to avoid loading it, I'll do then a `import { CKEditor } from 'd2-analysis/lib/ux/CKEditor';` in the app and remove that load from d2-analysis.

**Comment by tokland** [comment]
Can you check?

https://github.com/dhis2/d2-analysis/pull/64
https://github.com/dhis2/charts-app/pull/45

**Pull request merged**
